nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:9000'] # Add your frontend URL here
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type']
    paths:
        '^/': null
